# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\".\n\nAddRequest\x12\x0f\n\x07number1\x18\x01 \x01(\x05\x12\x0f\n\x07number2\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\"1\n\x0fMultiplyRequest\x12\x0e\n\x06input1\x18\x01 \x01(\x05\x12\x0e\n\x06input2\x18\x02 \x01(\x05\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32_\n\nCalculator\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponse\x12/\n\x08Multiply\x12\x10.MultiplyRequest\x1a\x11.MultiplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=66
  _globals['_ADDRESPONSE']._serialized_start=68
  _globals['_ADDRESPONSE']._serialized_end=97
  _globals['_MULTIPLYREQUEST']._serialized_start=99
  _globals['_MULTIPLYREQUEST']._serialized_end=148
  _globals['_MULTIPLYRESPONSE']._serialized_start=150
  _globals['_MULTIPLYRESPONSE']._serialized_end=184
  _globals['_CALCULATOR']._serialized_start=186
  _globals['_CALCULATOR']._serialized_end=281
# @@protoc_insertion_point(module_scope)
