replicaCount: 2

image:
  repository: rammurthymalisetti/feature-service
  tag: "v0.2"
  pullPolicy: IfNotPresent

imagePullSecrets: []
# imagePullSecrets:
#   - name: my-regcred

service:
  type: NodePort        # was ClusterIP
  port: 80              # service port inside cluster
  targetPort: 8080      # container port
  nodePort: 30080       # external port on node (must be 30000–32767)


resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

podAnnotations: {}

podLabels: {}

env:
  # Your Go app reads PORT env (we wired that earlier)
  PORT: "8080"

livenessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

nodeSelector: {}
tolerations: []
affinity: {}

