{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feature-service.fullname" . }}-postgres
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | b64enc | quote }}
  # Go app uses DATABASE_URL directly
  DATABASE_URL: {{ printf "postgres://%s:%s@%s-postgres:%d/%s?sslmode=disable" \
      .Values.postgres.username \
      .Values.postgres.password \
      (include "feature-service.fullname" .) \
      .Values.postgres.port \
      .Values.postgres.database | b64enc | quote }}
{{- end }}

